# This workflow will build a Java project with Gradle
# This file was contributed by EdwinBetanc0urt@outlook.com from ERP Consultores y Asociados, C.A
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Push Main Branches

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches:
      - develop
      - master

jobs:

  # Build dist application ADempiere-gRPC-Server
  build-app:
    name: Build dist ADempiere-gRPC-Server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: 8

      - name: get adempiere source
        run: |
          download_repo="https://github.com/erpcya/adempiere/releases/download/3.9.3-rs-4.3/Adempiere_393LTS.tar.gz"
          wget $download_repo -c -O Adempiere.tar.gz

      - name: uncompress file
        run: tar -xzf Adempiere.tar.gz

      - name: create dependences folder
        run: mkdir dependences
      - name: move dependences
        run: mv Adempiere/lib/*.jar dependences/
      - name: move packages
        run: mv Adempiere/packages/*/lib/*.jar dependences/

      - name: Build with Gradle
        run: gradle createRelease

      - name: Upload dist app zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: adempiere-gRPC-Server.zip
          path: build/release/adempiere-gRPC-Server.zip
      
      - name: move and unzip artifact
        run: |
          mkdir dist 
          mv build/release/adempiere-gRPC-Server.zip dist/
          cd dist
          unzip -o adempiere-gRPC-Server.zip
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          # CONFIGURE DOCKER SECRETS INTO REPOSITORY
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Lower Case to owner and repository
        run: |
          ORG=$OWNER
          if [ -n "${{ secrets.DOCKERHUB_ORG }}" ]; then
            echo "Set secret DOCKERHUB_ORG as namespace"
            ORG=${{ secrets.DOCKERHUB_ORG }}
          else
            echo "Set OWNER ($OWNER) as namespace "
          fi
          echo "ORG_LC=${ORG,,}" >> ${GITHUB_ENV}
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
          echo "REPO_LC=${NAME,,}" >> ${GITHUB_ENV}
        env:
          # to docker image namespace
          OWNER: '${{ github.repository_owner }}'
          NAME: '${{ github.event.repository.name }}'

      - name: Push image in Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build-docker/Dockerfile.prod
          push: true
          tags: |
            ${{ env.ORG_LC }}/${{ env.REPO_LC }}:latest
            ${{ env.ORG_LC }}/${{ env.REPO_LC }}:${{ github.sha }}
            ${{ env.ORG_LC }}/${{ env.REPO_LC }}:${{ github.event.release.tag_name }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


